name: PHP Lint

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

jobs:
  lint:
    name: Lint & Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          ini-values: memory_limit=1G, max_execution_time=0

      - name: Validate composer.json (non-strict then strict)
        run: |
          composer validate || true
          echo '---'
          composer validate || { echo 'Critical errors in composer.json - please fix them'; exit 1; }

      - name: Install dependencies (no dev optional)
        run: composer install --prefer-dist --no-progress

      - name: PHP syntax check
        run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      - name: Check coding standards (PSR-12)
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs --standard=PSR12 src
          else
            echo 'PHP_CodeSniffer not installed - skipping coding standards check'
          fi
