name: PHP Security

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Glueful security audit (production profile)
        run: |
          if [ -f vendor/bin/glueful ]; then
            php vendor/bin/glueful security:check --production || exit 1
          else
            echo 'Glueful CLI not installed - skipping security audit'
          fi
