name: Type System Gates

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Get Composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: PHPStan (repo-wide)
        run: composer phpstan

      - name: Type Gates (per-path strict checks)
        run: composer types:validate

      - name: Cache PHPStan result
        if: always()
        uses: actions/cache@v3
        with:
          path: phpstan.result.cache
          key: ${{ runner.os }}-phpstan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpstan-

